### ISSUE TITLE
`condition` doesn't seem to work

### ISSUE THREAD

**Issue by mikemaccana** [pateketrueke/yrv#1]
I have a `Route` with a condition, `showNavBar`, which shows a `Nav` component.

`<Route condition={ showNavBar } component={Nav} />`

`showNavBar` is set to `false` (shown from `console.log()`) but the Nav still launches!

Thanks for making `yrv`! 

```svelte
<script>

  import { Router, Route } from 'yrv';

  import Nav from './nav.svelte'
  import RecordEvents from './record-events.svelte'
  import ChatWidget from './chat-widget.svelte'
  import FrontPage from './front-page.svelte'
  import LoginPage from './login-page.svelte'
  import LaunchPage from './launch-page.svelte'
  import About from './about.svelte'
  import Pricing from './pricing.svelte'
  import Forgot from './forgot.svelte'
  import ForgotSent from './forgot-sent.svelte'
  import PrivacyPolicy from './privacy-policy.svelte'
  import Blog from './blog.svelte'
  import SignupPage from './signup-page.svelte'
  import ResetPasswordPage from './reset-password.svelte'
  import ErrorPage from './error-page.svelte'
  import Footer from './footer.svelte'

  let title = window.serverVars.title
  document.title = title

  var showNavBar = (! ['/login', 'signup'].includes(window.location.pathname))

  log({showNavBar})
</script>

<Router>  
  <Route condition={ showNavBar } component={Nav} />

  <Route exact path="" component={FrontPage} />
  <Route path="/about" component={About} />
  <Route path="/pricing" component={Pricing} />
  <Route path="/login" component={LoginPage} />
  <Route path="/launch" component={LaunchPage} />
  <Route path="/signup" component={SignupPage} />
  <Route path="/blog" component={Blog} />
  <Route path="/forgot" component={Forgot} />
  <Route path="/privacyPolicy" component={PrivacyPolicy} />
  <Route path="/forgotSent" component={ForgotSent} />
  <Route path="/resetPassword" component={ResetPasswordPage} />
  <Route fallback component={ErrorPage} error={window.serverVars.error}/>
</Router>

(More things here, cut for brevity)
```

**Comment by pateketrueke** [comment]
Hi, please use `condition` as a function, actually passing a scalar value will be removed due this kind of issue. 🙏

**Comment by pateketrueke** [comment]
Been said, I hope this fix your issue, since `0.0.12` the `condition` prop is required to be a function.

If you want to skip some routes based on state, you always can do the following:

```html
{#if showNavBar}
  <Route />
{/if}
```

I know is not as clear a binding a prop, but `condition` sounds to me as a _callable thing_ and not a bound property, in such case a `disabled` property could take its place if needed.

So much thanks for your input, have a nice week! :beers:

**Comment by mikemaccana** [comment]
Got it (and testing 0.0.12 now). 

Doesn't the `=` in Svelte already make it reactive?

**Comment by pateketrueke** [comment]
> Doesn't the = in Svelte already make it reactive?

Yeah, probably is a mistake on my implementation, let me find the use case where I did not made it work. 👍

**Comment by pateketrueke** [comment]
I just added support for `disabled` on both Route/Router components, so:

- Use `condition` to allow/disallow route-dispatching dynamically
- Use `disabled` to skip from rendering, it will add/remove the route

This new disabled prop would work as you're expecting:

```html
<Router disabled={!showNavBar}>
 ...
</Router>
```

Please let me know your thoughts on this, thank you!
