### ISSUE TITLE
Works very well than any other router i found for svelte

### ISSUE THREAD

**Issue by gokulkrishh** [pateketrueke/yrv#10]
Hi,

First of all let me thank you for creating this wonderful router. I was able to make it work for me from the example without any extra effort.

But i found it really hard to find a proper router for svelte. It would be great if we can change the name of the router to something very easy to find.

Just a proposal, `svelte-router-dom` or anything than makes this library easy found in npm search!.

**Comment by pateketrueke** [comment]
Package `keywords` did not worked too? I believe adding more keywords will suffice, otherwise renaming could be an option...

**Comment by gokulkrishh** [comment]
@pateketrueke Yes it worked. What i am saying is `svelte` is new framework for frontend. There isnt much router out there which works out of box properly. 

What i am suggesting is change the package name to something like `svelte-<somename>`

**Comment by pateketrueke** [comment]
Well, naming things is the hardest one... I'll consider it, but surely I won't change the name unless it become a deal-breaker for most users.

So much thanks for your input!

**Comment by gokulkrishh** [comment]
@pateketrueke Thanks. I am just suggesting. Leave it upto to you to decide.
