### ISSUE TITLE
Not working after deployment 

### ISSUE THREAD

**Issue by gokulkrishh** [pateketrueke/yrv#11]
Router is not working after deployment.

I have tried now.sh, surge.sh, netlify. Client side routing is not working after deployment.

Sample url: https://mybookshelf1.surge.sh/

**Comment by pateketrueke** [comment]
Hi, I found hard to debug what's going on with your app without access to its source-code, please provide it!

**Comment by gokulkrishh** [comment]
@pateketrueke Sure. Here is the [repo](https://github.com/gokulkrishh/bookshelf).

**Comment by pateketrueke** [comment]
Gotcha, please use the `<Link />` component to render your links, using regular `<a />` tags would not work as expected.

**Comment by gokulkrishh** [comment]
@pateketrueke I see. My bad i kind of missed it. but if a use wants to visit by url. It will not work right ?? May be worth considering ?

**Comment by pateketrueke** [comment]
> May be worth considering ?

It depends on the web-server settings, it should rewrite any URL to index.html to make it work.

**Comment by gokulkrishh** [comment]
@pateketrueke Browser Route in react-router-dom works without any web server settings.

**Comment by pateketrueke** [comment]
I mean, in sites like surge.sh you need to tell the web-server how to handle non pages, that's how push-state works; the real page does not exists, so if you ask directly the web-server it will serve the 404 page (exactly the way is behaving now) and no client-side library is capable of changing that...

**Comment by gokulkrishh** [comment]
@pateketrueke gotcha. Thanks
