### ISSUE TITLE
OnChange Event

### ISSUE THREAD

**Issue by ezetojo** [pateketrueke/yrv#13]
Is there any method that allows me to detect route change?
Or im doing things wrong? Im trying to make a fetch when my route changes.

**Comment by pateketrueke** [comment]
I think you can use the `$route` store in order to actually subscribe to any change:

```html
<script>
  import { Router, router, Link } from 'yrv';
  router.subscribe(info => { console.log('ON_CHANGE', info); });
</script>

<Link href="/foo">Foo</Link>
<Link href="/bar/buzz">Bar</Link>

<Router>
  {JSON.stringify($router)}
</Router>
```
