### ISSUE TITLE
Unexpected reserved word 'arguments' with svelte 3.19.1

### ISSUE THREAD

**Issue by gaou-piou** [pateketrueke/yrv#15]
[!] (plugin babel) SyntaxError: /home/christos/Works/NewLunonaDev/Lunona-svelte/node_modules/yrv/src/Route.svelte: Unexpected reserved word 'arguments'

With svelte 3.18.2 everything works as expected

**Comment by pateketrueke** [comment]
Interesting, I would prefer bublé over babel to avoid such kind of issues, but I'll take alook if I can fix that in our code... since we're relying on the `arguments` actually I need to found a way to achieve the same, thank you!

**Comment by gaou-piou** [comment]
fixed with svelte 3.19.2

**Comment by pateketrueke** [comment]
Oh, awesome, I'll keep this open until I found a good replacement for such hack.

So much thanks for your feedback!
