### ISSUE TITLE
<Link> used inside route component causes error

### ISSUE THREAD

**Issue by intermundos** [pateketrueke/yrv#18]
When I use **Link** inside component that is loaded into **Route**, clicking on the link causes error: 

![image](https://user-images.githubusercontent.com/16274871/77737881-e1094680-701f-11ea-9155-46158b53160a.png)

When **Link** is used outside the **Router** it works correctly

```bash 
<Link>link</Link>

<Router>
  <Route>
</Router>
 ``` 

```bash 
// Also using inside component loaded to Route does not work.
navigateTo(path)
 ``` 

Hope I explained well the issue.

Any help is appreciated.

**Comment by intermundos** [comment]
Here is some findings:

Issue happens with webpack builds.
Issue relates to:

-  [One](https://github.com/sveltejs/svelte/issues/3165)
- [Two](https://github.com/qutran/swheel/issues/7)


Solution for webpack powered project:

1. Add mainFields into resolve config
```bash
 mainFields: ['svelte', 'browser', 'module', 'main']
```
2. Remove exclude: /node_modules/ from svelte-loader config

This solution works only if no style tags present in yrv components - Router/Route that has style tag with [data-failure] selector. 

May I suggest we move these styles into inline style attribute to avoid further problems in using the router in complex setups?

I will submit a PR for this for your consideration.

**Comment by pateketrueke** [comment]
Actually the issue sound funny, can you replicate that on the official [Svelte REPL](https://svelte.dev/repl/)?

**Comment by intermundos** [comment]
Yes, sorry, after investigating it was not related to Link used inside the Route, but rather to svelte problem with dealing with node modules packages and svelte multiple instances, as far as I understood. The solution I mentioned solves it, but crashes on compilation of style tags I mentioned before. 

I will try to set up REPL and see whats going on.

**Comment by intermundos** [comment]
Not relevant anymore. 

Checked on REPL and it worked. Rollup config used similar setup to webpack with "dedupe" field in resolve config to include only one instance of svelte. 

Same is achieved with "mainFields" config of webpack resolve.

As to css failed to compile, I missed webpack config to pickup styles from yrv module.

**Comment by pateketrueke** [comment]
No worries, I really understand the potential causes, may be we can translate this knowledge into something useful for new users?

Actually adding a quick FAQ section would help, optionally of course, no pressure.

Again, so much thanks for your feedback!
