### ISSUE TITLE
Inconsistency with path="" vs path="/"

### ISSUE THREAD

**Issue by mikemaccana** [pateketrueke/yrv#2]
Heya. Here's a subtle issue with the route for `/`, the top level of my site:

Using yrv `0.0.12`, the following will break

```
<Router>
  <Route exact path="" component={FrontPage} />
  <Route path="/about" component={About} />
  <Route path="/pricing" component={Pricing} />
  <Route path="/login" component={LoginPage} />
  ...
```

I can fix it with (note the `path` on the first line):

```
<Router>
  <Route exact path="/" component={FrontPage} />
  <Route path="/about" component={About} />
  <Route path="/pricing" component={Pricing} />
  <Route path="/login" component={LoginPage} />
  ...
```

Note while this works, it's a bit inconsistent - `/about` has no trailing slash.,`/pricing` has no trailing slash, why does `` need a trailing slash? 

Ideally / should be normalised and the trailing / not needed.

**Comment by pateketrueke** [comment]
Sure, I also found a similar issue on svelte-repl, where there are no `history` available and the home-route should be rendered by default but it does not, until you click on the nav-link: https://svelte.dev/repl/0f07c6134b16432591a9a3a0095a80de?version=3.12.1

I hope it is related, I'll be working on them asap, so much thanks for your input! :beers:

**Comment by pateketrueke** [comment]
I've been thinking that routes should start either with `/` or `#` so an empty string will also be deprecated imho.

The `/` alone is not a trailing slash but a leading one, so all routes should have a leading slash to be consistent.

What do you think?

**Comment by mikemaccana** [comment]
> The / alone is not a trailing slash but a leading one, so all routes should have a leading slash to be consistent.

That's an excellent point. I'd argue that both `''` and `'/'` should work - see https://en.wikipedia.org/wiki/Robustness_principle

**Comment by pateketrueke** [comment]
Oh, I just added a validation to reject routes that does not starts with `/` or `#` and the current release, do you think we should allow and empty string too?

E.g.

```html
<Route>OK</Route>
<Route path="/">OK</Route>
```

Above, both routes are equivalent, if we allow empty strings now we'll have three ways to do the same.

I'm fine with that, but if you ask me I would opt for not adding the `path` instead of using an empty string as its value.
