### ISSUE TITLE
Trailing slash handling

### ISSUE THREAD

**Issue by AlexxNB** [pateketrueke/yrv#21]
For example we have route like:
```
<Route exact path="/auth" component={Auth}/>
```
Using SPA navigation  without any troubles. But when run app on production, some servers may redirect URL like `http://mydomain/auth` to  `http://mydomain/auth/` - with trailing slash. In this case router won't show the needed page. Usually, it is configurable on the server side - but maybe it is better to add support for both URL in the router?

**Comment by pateketrueke** [comment]
Yeah, why not? Let me se what can I do, thank you!

**Comment by pateketrueke** [comment]
I ended adding support for this to fix nested routers, is ready on master if you want to play around. 💣

**Comment by AlexxNB** [comment]
Great! Thank you!
