### ISSUE TITLE
Dynamic component not functioning

### ISSUE THREAD

**Issue by jhechtf** [pateketrueke/yrv#22]
**YRV Version:** 0.0.27
**Svelte:** 3.20.1

Okay, so let's get ready for a fairly long ticket -- trying to be as thorough as possible to make sure I'm documenting what I am seeing.

## Description

According to the readme, the following should work by dynamically importing the '404.svelte' file:
```html
<script>
import {Router, Route} from 'yrv';
import Dashboard from './dashboard.svelte';
</script>
<Router>
  <Route component={Dashboard} path="/" exact />
  <Route component={() => import('./_404.svelte')} fallback pending="Loading..." />
</Router>
```

However, all I am seeing on the page is 'Loading...'

Switching this to something a little bit more wordy, such as 

```html
<script>
// same stuff
</script>

<Router>
  <Route component={Dashboard} path="/" exact/>
  <Route component={() => {
    console.log('Testing');
    return import('./_404.svelte');
  }} fallback pending="Whoops"/>
</Router>
```
never shows 'Testing' in the console -- this function is never called. **BUT** if we re-arrange that to 
```html
<script>
// same imports
  function loadMe(){
    console.log('Load Me!')
    return import('./_404.svelte').then(res=>{
      console.log(res);
      return res;
    });
  }
</script>

<!-- Creates an index route with an errorpage fallback -->
<Router>
  <Route component={Dashboard} path="/" exact/>
  <Route component={loadMe} fallback pending="Whoops"/>
</Router>
```
I now see "Load Me!" in the console, but I receive this error:

```
Route.svelte:224 Uncaught (in promise) TypeError: Cannot read property 'fragment' of undefined
    at Object.create [as c] (Route.svelte:224)
    at Object.create [as c] (Route.svelte:90)
    at Object.update [as p] (Route.svelte:607)
    at update (index.mjs:834)
    at flush (index.mjs:803)
```

In fiddling around I thought maybe the arrow function binding messed something up and the end function needed to be bound differently, so I changed the given `<Route>` to read:

```
<Route component={loadMe.bind(this)} fallback pending="Whoops" />
```
Which _removes_  the error, but no longer shows 'Load me!' to indicate the function has been invoked.

Out of sheer morbid curiosity I decided to change the function declaration for `loadMe` to the following:

```html
<script>
// same includes
const loadMe = () => {
  console.log('Load Me!');
  return import('./_404.svelte');
}
</script>
<Route component={loadMe} fallback pending="Whoops" />
```
Which likewise no longer shows 'load me!'
## Other Information

**Does `import('./_404.svelte')` work?**
Yes -- if I add a `.then(res => { console.log(res); return res; })` to it and just have it load passively in the component it works just fine.

**Comment by pateketrueke** [comment]
Interesting, seems like it fails on `fallback` routes only, thank you!
