### ISSUE TITLE
Hash-based routes?

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#23]
What it really means `Hash and URI-based routes` in Readme.md?

I can use hash-based routes à la Gmail? e.g.: `index.html#/profile`, `index.html#/book/42`?

**Comment by pateketrueke** [comment]
Yeah, exactly that.

URIs like that are suitable for embedded apps like Electron, where normal URLs would fail.

Also this mode is the default used on the Svelte REPL, because is not an iframe, nor a regular webpage... it's a weird thing!
