### ISSUE TITLE
<Component> was created with unknown prop 'router'

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#25]
On every `Component` in my `Router` i get this warning in browser's console.

`was created with unknown prop 'router'`

Can we do anything to remedy this?

**Comment by frederikhors** [comment]
I opened this: https://github.com/sveltejs/svelte/issues/4652.

We'll see.

**Comment by pateketrueke** [comment]
> Can we do anything to remedy this?

Yes, just add this on every component you import in:

```html
<script>
export let router = null;
</script>
```

No matter if you're not using such prop, but remember warnings are not bad, just a reminder that you should not ignore, unless you got its meaning.

**Comment by frederikhors** [comment]
As stated here: https://svelte.dev/docs#1_export_creates_a_component_prop

> In development mode (see the compiler options), a warning will be printed if no default initial value is provided and the consumer does not specify a value. To squelch this warning, ensure that a default initial value is specified, even if it is undefined.

I think it's wrong to use: `export let params = undefined` (or the same `export let params`, or `null`) just for a warning at develop time.

Code compiled with `export let params` is different from code compiled without.

If there are a lot of `<Components>` the code increases and I don't see the reason.

What changes at the operating level?

**Comment by pateketrueke** [comment]
> What changes at the operating level?

I'm unaware of that, but adding the required props is free.

**Comment by pateketrueke** [comment]
I've been thinking about this and definitely is not a `yrv` bug or issue, if you plan to setup route-components there will be minimum requirements (a warning thrown by the compiler is outside libraries scope).

I am almost sure that most libraries suffer of this _issue_ during development.

If you think this is not quite right then please raise an question/issue on the offical Svelte repositories, thank you.

**Comment by frederikhors** [comment]
> If you think this is not quite right then please raise the question/issue on the official Svelte repositories, thank you.

Already did: https://github.com/sveltejs/svelte/issues/4652.

And `svelte-pa-router` author too: https://github.com/sveltejs/svelte/issues/4649.

We'll see.

Please if you can write something on this you too, thanks: https://github.com/sveltejs/svelte/issues/4652.
