### ISSUE TITLE
Nested routers are not working

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#26]
REPL: https://svelte.dev/repl/339508656b994703a75f3e99c4f47d8c?version=3.20.1

Going on `/players` I expect <List> to appear.

**How come it doesn't appear?**

**Comment by pateketrueke** [comment]
> How come it doesn't appear?

Good catch, and really good question! 🤔 

So much thanks for your feedback, I'll investigate on this asap.

**Comment by frederikhors** [comment]
This is the most URGENT.

I can't migrate from other routers.

Unless I use many `Router/>` on the `App.svelte` but it's a mess.

**Comment by pateketrueke** [comment]
Hi, I found the solution for this bug but I'll release it once I close the other issues. 😉
