### ISSUE TITLE
Conditional crash

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#32]
REPL: https://svelte.dev/repl/01a444e9c31045e5901ee9d51c32551a?version=3.20.1

I expect to see "This is Login" when I uncheck checkbox.

What is wrong with it?

**Comment by frederikhors** [comment]
This is a version with conditional not in <Router/>: https://svelte.dev/repl/253d93fe449e4e8c9ae2ebc3cfaeaf22?version=3.20.1

**Comment by pateketrueke** [comment]
Investigating. 🍻

**Comment by pateketrueke** [comment]
The second version you posted does not work? Weird... I found a way to test out your code locally, so I can inspect everything:

- create a folder for the issue, e.g. `./e2e/nested-routers`
- put all your REPL componentes there renaming imports from `yrv` to `../../src`
- in `./e2e/main.js` just import the desired entry-point from the created folder above
- type `make dev` and start debugging!

**Comment by frederikhors** [comment]
> The second version you posted does not work? Weird...

Yes and there is a more serious problem if you uncheck on /players page:

![image](https://user-images.githubusercontent.com/41120635/79009130-1e60ee80-7b5f-11ea-90ba-d1309f6e8f49.png)

**Comment by pateketrueke** [comment]
Yup, I noticed that too! :beers:

I think I already solved it, but now I'm adding your tests, so any further investigation could happen there.

> 🔧 Also it will be the basis for adding more scenarios or especial cases, tests, etc.

**Comment by frederikhors** [comment]
> I think I already solved it

Can you release, please?

**Comment by pateketrueke** [comment]
Still not working, according the REPL, once you re-enable the `isLoggedIn` checkbox the NotFound handler vanishes... 🐛

**Comment by frederikhors** [comment]
The second REPL works good now!

**Comment by pateketrueke** [comment]
I found the _solution_ for the first-issue:

```diff
<Router>
  {#if isLoggedIn}
    <Route exact component="{Home}" />
    <Route path="/players" component="{Players}" />
-    <Route fallback component={NotFound} />
+    <Route key="fix" fallback component={NotFound} />
  {:else}
-    <Route fallback component={Login} />
+    <Route key="fix" fallback component={Login} />
  {/if}
</Router>
```

The `key` should not be the same, but in this context seems to be fine.

It helps `yrv` to identify back the fallback, by key, once it is mounted again! :beers:

> When `yrv` registers a new route, it checks if there's a `key` given on the route, a random key is generated to identify the route/component otherwise.
>
> When routes are detached they're also removed from the router registry, so it destroys everything (which is fine) but due that, the next time the same route is mounted a new key is generated.
