### ISSUE TITLE
Better clarify differences between promise and async import

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#33]
Can we better clarify the difference between these two import modes?

```svelte
<Route exact path="/promise" component={import('path/to/other-component.svelte')}/>
<Route exact path="/async" component={() => import('path/to/another-component.svelte')}/>
```

**Comment by pateketrueke** [comment]
> Yes, I think `async` is a bad name, because it performs the loading _lazily_ so it should be named **lazy** instead. 🤔 

Behind the scenes, for making dynamic-imports work, the bundler actually _can_ inline such import or just write-out the required chunks to make it work natively (`<script type="module" />`) or through `shimport`, etc.
