### ISSUE TITLE
Global or Router pending component

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#34]
Using something like this:

```svelte
<Router>
  <Route exact path="/lazy1" component={() => import('path/to/another-component1.svelte')} pending={Loading}/>
  <Route exact path="/lazy2" component={() => import('path/to/another-component2.svelte')} pending={Loading}/>
  <Route exact path="/lazy3" component={() => import('path/to/another-component3.svelte')} pending={Loading}/>
  <Route exact path="/lazy4" component={() => import('path/to/another-component4.svelte')} pending={Loading}/>
</Router>
```

I think we need something to avoid repetition of `pending={Loading}`.

Maybe a pending on `<Router/>` like this:

```svelte
<Router pending={Loading}>
```

or better something like:

```svelte
import { Router } from 'yrv';

Router.pending={Loading}
```

What do you think about?

**Comment by frederikhors** [comment]
Maybe in case of nested routers and a solution for `<Router pending={Loading}/>` we can avoid repetition of `pending...` for sub-routers...

**Comment by pateketrueke** [comment]
Sounds fair, the same as `exact` from top-level routers.

My only concern on inheriting stuff from routers is keeping the context safe, e.g.

```html
<Router exact>
  <Route a />
  <Route b />
  <Router>
    <Route c />
  </Router>
</Router>
```

The nested-router here should not inherit the `exact` down to its routes or it should? 🤔 

So, `a` and `b` are exact routes, but `c` should be exact too or not?

**Comment by frederikhors** [comment]
I think every Router should inherit from parent but can set its context.

Is it wrong?

**Comment by pateketrueke** [comment]
> Is it wrong?

I'm not sure, but think about this: imagine you don't known that the top-level router is exact, and you mount some routes somewhere else inside its context.

You put some routes that are not exact, but suddendly they behave as exact, because its parent router inherited the exact prop from the top-level router.

Do you think that is completely expected?

> I would not inherit from router to router, only routes should inherit stuff from its parent-router, and nothing else — that makes perfect sense to me.

**Comment by frederikhors** [comment]
> IMHO I would not inherit from router to router, only routes should inherit stuff from its parent-router, and nothing else — that makes perfect sense to me.

Makes sense. Go with it! :)

**Comment by jhechtf** [comment]
In theory I have some code that would work for this issue. I simply cannot get your testing setup to work for me no matter what computer I try it on though, so I'm unsure if I a breaking anything.

**Comment by pateketrueke** [comment]
@jhechtf please rebase again from the master branch, after that you can `make ci` to run all the tests in your computer, or just wait for github actions to complete. Thank you!

**Comment by jhechtf** [comment]
@pateketrueke I rebased the commit some time ago (during thanksgiving break), but as I've said I'm unable to run unit tests in the repository so I cannot attempt to make unit tests to see if my fix does what is intended for this ticket.

**Comment by pateketrueke** [comment]
Really there is no way to run the suite test in your system? I'm intrigued, please share the logs to see what's happening.

**Comment by jhechtf** [comment]
Depending on which environment I use, 

```

ERROR Unable to find the browser. "chrome:headless" is not a browser alias or path to an executable file.

Type "testcafe -h" for help.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yrv@0.0.35 test:e2e: `cross-env BASE_URL=http://localhost:3000 testcafe ${BROWSER:-chrome:headless} "-a" "npm run dev" "e2e/cases" "--color"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yrv@0.0.35 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jhecht/.npm/_logs/2020-12-05T09_03_26_373Z-debug.log
npm ERR! Test failed.  See above for more details.
make: *** [Makefile:9: ci] Error 1
```
is the farthest it goes. otherwise it stops way before that.

**Comment by pateketrueke** [comment]
So, you don't have Chrome installed? Try another browser instead, e.g. `make ci BROWSER=chromium:headless` or `make ci BROWSER=firefox` or `make ci BROWSER=safari`  instead.

**Comment by jhechtf** [comment]
I don't do work on a Linux distribution, so neither of these solutions work for me.

**Comment by pateketrueke** [comment]
Do you have access to Docker?
