### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by frederikhors** [pateketrueke/yrv#35]
I have tried to analyze the final weight impact in my application.

![image](https://user-images.githubusercontent.com/41120635/79022207-b5d53a00-7b7d-11ea-93dc-1a8f682489ce.png)

Compared to `svelte-spa-router`:

![image](https://user-images.githubusercontent.com/41120635/79022668-c639e480-7b7e-11ea-99de-05ea36c11774.png)

https://bundlephobia.com/result?p=yrv@0.0.30

Not just 10 KB.

Final bundle's size is different:

![image](https://user-images.githubusercontent.com/41120635/79022909-4e1fee80-7b7f-11ea-8f0d-aff630a43bef.png)

With `svelte-spa-router`:

![image](https://user-images.githubusercontent.com/41120635/79022895-44968680-7b7f-11ea-8fd7-5dc78c95d913.png)

Many `src/*.svelte` have a lot of stuff more with `yrv`.

And finally `query-string` about 3 KB.

25 KB more is huge!

Can I ask you why and if there is a way to "fix"?

**Comment by jhechtf** [comment]
**Disclaimer: I am not affiliated with this project**

That is the raw version of the files / the entirety of the svelte components before being put through the bundler / compiler. If you install YRV and check the actual files in the node_modules, you'll notice a `dist/` folder that has 3 files, all of which are < 30kB. During a production bundle / build your bundler should use those instead of the raw source files. 

All of that being said, why is an extra 0.07 seconds (assuming a 3 Mb/s connection) that big of a deal?

**Comment by frederikhors** [comment]
> That is the raw version of the files / the entirety of the svelte components before being put through the bundler / compiler. If you install YRV and check the actual files in the node_modules, you'll notice a `dist/` folder that has 3 files, all of which are < 30kB. During a production bundle / build your bundler should use those instead of the raw source files.

Not really.

I'm talking about production-ready size.

> All of that being said, why is an extra 0.07 seconds (assuming a 3 Mb/s connection) that big of a deal?

Is not about pure numbers. Is about how much code the CPU needs to analyze to render the page. And if you are using a very small CPU on very small HW then every extra byte weighs!

**Comment by frederikhors** [comment]
`yrv` is a magnificent project!

We should address bundle size now and it'll be beautifully fantastic!

**Comment by pateketrueke** [comment]
> Can I ask you why and if there is a way to "fix"?

I'm not sure. 🤔 

The goal of `yrv` is not to be the smallest or fastest, but flexible and fun with enough features.

It has the features I wanted but no other routers provided me, so I prefer to pay the size to get more stuff quickly!

We can try to make `query-string` pluggable, e.g. `Router.qs = queryStringModule` — but the other source files are hard to reduce, or make them tree-shakeable.

> I mean, I'm not against reducing the bundle-size but that's very subjective, at the end your main application should be your main concern as dependencies can be changed over time, dunno.

**Comment by frederikhors** [comment]
I'm trying to understand:

![image](https://user-images.githubusercontent.com/41120635/79041158-c624fd80-7bed-11ea-8588-3ce49352e3a9.png)

**Comment by frederikhors** [comment]
I created https://github.com/pateketrueke/yrv/pull/36 for investigation.

**Comment by frederikhors** [comment]
First, small reduction in https://github.com/pateketrueke/yrv/pull/37.

**Comment by frederikhors** [comment]
Second reduction: about 2 KB: https://github.com/pateketrueke/yrv/pull/38.

This is a test.

Removing all the code for GUI error/failure handling for a single `console.error(err)` I can save 2 KB.

It would be great to be able to use graphical error messages only in `development` mode and not in `production`.

What do you think about it?

**Comment by frederikhors** [comment]
It would be useful to implement tree-shake also `abstract-nested-router` and `query-string`.

**Comment by frederikhors** [comment]
We can make `query-string` optional.

**Comment by pateketrueke** [comment]
> It would be useful to implement tree-shake also for abstract-nested-router and query-string.

The `abstract-nested-router` is at its minimum, I'm using all their methods on `yrv`.

But for `query-string` yeah, we should make it optional!

**Comment by pateketrueke** [comment]
Hi, I've been working on this task and I have something you can help me test out:

- On `master` I've setup a new bundler that supports kind-of _macros_ to disable entire code blocks
- If you run `npm run prepublishOnly` you'll got a stripped version from the same `./src` files without DEBUG blocks

I hope that helps to reduce the final size, please let me know if this is useful, thank you!

**Comment by pateketrueke** [comment]
Fixed on  `v0.0.33` — check out the [FAQ's](https://github.com/pateketrueke/yrv#frequently-asked-questions)
