### ISSUE TITLE
Example of <Routers> spread across components?

### ISSUE THREAD

**Issue by tyteen4a03** [pateketrueke/yrv#42]
I have this setup:

App.svelte:
```
<main>
    <Navbar />
    <div class="master-container {extraClassesString}">
        <Router>
            <Route exact path="/" component={IndexPage} />
            <Route path="/blog" component={BlogListPage} />
            <Route fallback component={NotFoundPage} />
        </Router>
    </div>
</main>
```

BlogListPage.svelte
```
    ... some common header stuff
    <Router path="/blog">
        <Route exact path="/:year/:id" let:router>{router.params.year} {router.params.id}</Route>
    </Router>
```

Can you provide an example of how to make this routing configuration work?

**Comment by pateketrueke** [comment]
The `<Router />` used in `BlogListPage.svelte` should not have path, as it is taken from the route where it was mounted.

Your current setup would work if you use a link like `/blog/blog/1/2` — because you declared the same path twice.
