### ISSUE TITLE
Component props

### ISSUE THREAD

**Issue by ivanbara** [pateketrueke/yrv#45]
Hi,

Thanks for an excellent svelte router.

How would one pass props to routed components? 

E.g.:
` <Route exact path="/#faq" component={<FAQ prop1=true/>} /> ? (this doesn't work)`

**Comment by pateketrueke** [comment]
Any additional property you assign to `<Route />` will be passed down (except private props), e.g.

```html
<Route exact path="/#faq" component={FAQ} prop1=true/>
```
