### ISSUE TITLE
Change the tagline to something more inclusive

### ISSUE THREAD

**Issue by ItalyPaleAle** [pateketrueke/yrv#46]
I'm writing a book about development with Svelte. I like the work you've done, so I'd like to recommend yrv as the router for people who want to use one based on the HTML5 history API.

However, the tagline for the project ("Your routing bro!") makes me feel uncomfortable and stops me short of doing that. This is present on GitHub at the top of the page, as well as in multiple parts in the code: https://github.com/pateketrueke/yrv/search?q=bro&unscoped_q=bro 

Would you please consider changing the tagline to something more inclusive? The "bro" term is connected to a [toxic culture](https://www.vox.com/2018/2/5/16972096/emily-chang-brotopia-book-bloomberg-technology-culture-silicon-valley-kara-swisher-decode-podcast) in tech (you might have heard the term "brogrammers") that is hurting women and non-binary individuals.

Your code is really good, there's no reason why "non-bros" can't use it 😉

**Comment by pateketrueke** [comment]
Oh, sounds fair to me sorry for that, but I'm short of options... what can I used innstead? Thank you.

**Comment by ItalyPaleAle** [comment]
Thanks for considering this!

Uhm what do you think about “Your router friend”?

**Comment by pateketrueke** [comment]
I'm very sorry on this, since I'm not english-native speaking I never thought about the implications of that word.

Sincerely I apologize for that and I'll be more aware about such words in my future work.

**Comment by ItalyPaleAle** [comment]
It's all good, thanks for being open to making this change and acting quickly! 😄
