### ISSUE TITLE
warning with rollup on compile in Route.svelte

### ISSUE THREAD

**Issue by sachinbhutani** [pateketrueke/yrv#5]
(!) Plugin svelte: Route has unused export property 'props'. If it is for external reference only, please consider using `export const 'props'`
node_modules/yrv/src/Route.svelte
27:   export let key = null;
28:   export let path = '/';
29:   export let props = null;
                 ^
30:   export let exact = null;
31:   export let disabled = false;

**Comment by pateketrueke** [comment]
Interesting, let me explore this stuff, thank you!

**Comment by sachinbhutani** [comment]
Thanks for fixing it so quick, 
I built a rust backend + svelte starter using YRV. Tried with svero first, but that didn't work. 
Would not have  been possible without YRV
https://github.com/sachinbhutani/svelte-on-rust

Please add "svelte-router" keyword to your repo, as it doesn't showup when I was looking for a router, only found reference in an issue on svero.

**Comment by pateketrueke** [comment]
> Please add "svelte-router" keyword to your repo, as it doesn't showup when I was looking for a router, only found reference in an issue on svero.

Sure, thank you!
