### ISSUE TITLE
Route with id param messes up stylesheet.

### ISSUE THREAD

**Issue by AndreasHald** [pateketrueke/yrv#53]
Hi i've been using this router to get to know Svelte, and so far all good.

But when i got to creating a route with an id parameter, refreshing the page on that route causes the app to look for the stylesheet in the wrong place.

![Screenshot 2020-09-08 at 15 54 58](https://user-images.githubusercontent.com/8914722/92486226-1ed3e300-f1ec-11ea-8557-c3d31ded3f4b.png)

![Screenshot 2020-09-08 at 15 55 19](https://user-images.githubusercontent.com/8914722/92486239-23000080-f1ec-11ea-8e6c-1897ca089369.png)

instead of looking for ``index.css`` in ``localhost:4200/index.css`` like all other routes, this one for some reason attempt to look in a nested folder.

Thus if i navigate around, starting somewhere else, no problem. But if i refresh the page on ``http:localhost:4200/report/1234`` it won't find the stylesheet.

Any ideas?

Index.html for reference

![Screenshot 2020-09-08 at 16 00 58](https://user-images.githubusercontent.com/8914722/92486538-82f6a700-f1ec-11ea-890b-681cf09c7b8c.png)

**Comment by pateketrueke** [comment]
You can try:

- an absolute path for `/index.css`
- setup a `<base href="/">` instead

**Comment by AndreasHald** [comment]
This actually had nothing to do with ``yrv``.

It was caused to a relative path to index.css as you correctly pointed out @pateketrueke, i fixed it by having tailwind compile to another file in the build directory and link to that instead.

Sorry for opening this issue, closing again.
