### ISSUE TITLE
Support on:click for Link(button) without href

### ISSUE THREAD

**Issue by ZerdoX-x** [pateketrueke/yrv#56]
Started from here: https://github.com/pateketrueke/yrv/issues/47

**Comment by ZerdoX-x** [comment]
So button is disabled if no link passed. I guess it's not good because Link (with <a> tag) without href passed works well

**Comment by ZerdoX-x** [comment]
Workaround — pass disabled prop with "false" value:
`<Link button on:click="{() => alert(1)}" disabled="{false}">...</Link>`

**Comment by pateketrueke** [comment]
> Interesting, buttons are disabled if they're active, because they are used to navigate, the same as for regular links: it won't trigger the same action twice, hence the disabled attribute on buttons.
>
> IMHO I would not use links or buttons if they're not for navigation, probably I'll remove the example too as it leads to unwanted behaviors.
