### ISSUE TITLE
Support for cmd+click open in new window

### ISSUE THREAD

**Issue by csell5** [pateketrueke/yrv#57]
@pateketrueke thank you for the great work on YRV. We've heavily used it with that.us (github.com/thatconference/that.us).

I don't know if I am doing something wrong, or if it's just not supported but is there a way to support cmd+click where you open that link in a new window?

Thanks!
Clark

**Comment by pateketrueke** [comment]
You're right, yrv does not support that... yet!

I think is easy to fix as you provided in your comments, let me see if I can fix asap and release.

However, if you want to tackle this one I'll be glad to review your submission, thank you.

**Comment by csell5** [comment]
I'll get it a shot or at least get it rolling. I should only need to change Link and navigateTo correct?
