### ISSUE TITLE
Link component href not updating when bound

### ISSUE THREAD

**Issue by vypxl** [pateketrueke/yrv#7]
```html
<script>
export let path = '/'
</script>

<Link href={path}><fancy stuff /></Link>
```

When I try to create a dynamic link like this, the corresponding `<a>` tags `href` attribute does not reflect the change of the `path` variable. It does, however, lead to wherever `path` points to when clicked.

So when I change the `path` from `/` to `/about`, the `href` is still `/`, but when I click on the link, it leads me to `/about`.

**Comment by pateketrueke** [comment]
Oh, yeah, I actually did not handled such attribute as expected.

Let me see if I can fix it quickly, thanks for your feedback!
