### ISSUE TITLE
Dynamic Imported Components

### ISSUE THREAD

**Issue by jhechtf** [pateketrueke/yrv#9]
Great library, glad to have it!

Quick question though -- I come from a largely Vue background and I was wondering if there was any way implement Vue's dynamic import? e.g.

```html
<script>
import {Router, Route} from 'yrv';
</script>

<Router>
  <Route component={() => import('./pages/SomePage.svelte')} path="/some-page" />
  <Route fallback>
    Whoops!
  </Route>
</Router>
```

I figured I'd ask here and see if it is a feature you can implement yourself (I've not looked at the source) or if it should be asked further up the pipeline.

Thanks!

**Comment by pateketrueke** [comment]
Oh, nice question, I haven't look at it yet... I need some time to explore this, thank you!

**Comment by pateketrueke** [comment]
Hi, now you can use the `dynamic` and `pending` attributes for that, e.g.

```html
<Route dynamic={import('./your/component.js')} pending="Loading ..." />
```

**Comment by jhechtf** [comment]
Love it, you're golden!

**Comment by intermundos** [comment]
Hello folks,

@pateketrueke  thanks for sleek router. 

I've been playing with it lately, but couldn't manage it to work dynamically. I did as specified above, but the component I try to load dynamically appears in the browser straight on load. 

```js
   <Route path="/World" dynamic={ import(/* webpackChunkName: "async" */'@/components/async.svelte') } pending="Loading..."/>
```

On network it appears straight away. 

![image](https://user-images.githubusercontent.com/16274871/77341099-e3755300-6d36-11ea-9113-51f478436b32.png)

Any help is appreciated.

**Comment by pateketrueke** [comment]
Oh yeah, I see what you mean, the component should not be loaded until it's really needed.

Probably we need a special way to lazily inline those promsies wheen needed, e.g.

```html
<Route dynamic={() => import(...)} />
```

I think we can detect if its value is a function or a promise... based on that we can then delay the actual loading of the underlying component.

What do you think?

**Comment by intermundos** [comment]
Thanks for swift reply!

I think this kind of functionality would be great. Tough may cause some misunderstanding of what exactly does dynamic prop.

May be it would be better to have "dynamic" prop only for async loading of components on demand, while "component" prop may have this functionality of getting either svelte component or import statement.

**Comment by pateketrueke** [comment]
> May be it would be better to have "dynamic" prop only for async loading of components on demand, while "component" prop may have this functionality of getting either svelte component or import statement.

I like that, would you mind on opening a PR with those changes?

**Comment by intermundos** [comment]
Sure, I will try 👍

**Comment by intermundos** [comment]
Submitted PR:
[Dynamic components](https://github.com/pateketrueke/yrv/pull/17)

**Comment by intermundos** [comment]
Resolved in [Dynamic components](https://github.com/pateketrueke/yrv/pull/17).
